### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Wayder228** [ErikPDev/LimitCreative#1]
please help what is this?
![Screenshot_2022-04-18-12-01-20-495_com estrongs android pop](https://user-images.githubusercontent.com/94379553/163786538-404fb048-b4de-4539-9935-848d8822766f.jpg)

**Comment by ErikPDev** [comment]
Well. That error is depressing.

**Comment by ErikPDev** [comment]
I'm working on a workaround on this.

**Comment by Wayder228** [comment]
cheers thanks, you can quickly, you can even just ban the barrel, many do not need it.

**Comment by Wayder228** [comment]
> Я работаю над обходным путем для эт You can disable the barrel or do something, players can open it in the GM.

**Comment by ErikPDev** [comment]
Fixed in latest build.

**Comment by Wayder228** [comment]
> Исправлено в последней сборке.

thank you very much, you are the only one who made this plugin.
