### ISSUE TITLE
add a barrel

### ISSUE THREAD

**Issue by Wayder228** [ErikPDev/LimitCreative#2]
I add a barrel to the config, and you can open it all the way
- "barrel"

**Comment by ErikPDev** [comment]
Send your entire config.yml

**Comment by Wayder228** [comment]
> Отменить весь config.yml
I'll send it right now.
![Screenshot_2022-04-23-19-03-26-354_com estrongs android pop](https://user-images.githubusercontent.com/94379553/164913871-0753d516-a371-4ed9-b2c7-1f5459170da6.jpg)

**Comment by Wayder228** [comment]
> Отменить весь config.yml

here

**Comment by Wayder228** [comment]
> Отправьте весь config.yml

Ну что?

**Comment by ErikPDev** [comment]
Fixed in latest dev, tell me if it works.

**Comment by Wayder228** [comment]
> Исправлено в последней версии, скажите, работает ли это.

did not have time to check, but the server in the last assembly crashes every five minutes.

**Comment by Wayder228** [comment]
> Исправлено в последней версии, скажите, работает ли это.

I used 5 of your assembly before, it works fine, only the barrel can be opened :(

**Comment by Wayder228** [comment]
> Fixed in latest dev, tell me if it works.

sorry, I made a mistake, it was not your plugin that crashed. I'll check if it works right now.

**Comment by Wayder228** [comment]
> Исправлено в последней версии, скажите, работает ли это.
thanks, I also advise you to disable the frame in the default config.

**Comment by ErikPDev** [comment]
Sure, I'll implement that later tonight.

**Comment by Wayder228** [comment]
> Конечно, я реализую это позже сегодня вечером.

Your plugin is the best of its kind.
