### ISSUE TITLE
Erorr every 5 minutes.

### ISSUE THREAD

**Issue by Wayder228** [ErikPDev/LimitCreative#3]
Please fix.
![Screenshot_2022-04-24-17-00-22-493_com estrongs android pop](https://user-images.githubusercontent.com/94379553/164980239-a91bcf6e-5284-4f0a-ae51-b6a81bd18628.jpg)

**Comment by ErikPDev** [comment]
Try the latest dev build

**Comment by Wayder228** [comment]
> Попробуйте последнюю сборку для разработчиков

Thanks
