### ISSUE TITLE
latest build

### ISSUE THREAD

**Issue by Wayder228** [ErikPDev/LimitCreative#4]
Here is the error 2 hours ago, latest version.
![Screenshot_2022-04-28-13-18-57-451_com estrongs android pop](https://user-images.githubusercontent.com/94379553/165731872-845fc62b-2190-4cb3-9627-ddddf6a91086.jpg)

**Comment by ErikPDev** [comment]
I'll just strip out the effect saving

**Comment by Wayder228** [comment]
> Я просто уберу эффект сохранения

well.

**Comment by ErikPDev** [comment]
Removed, remember to delete the old database.
